CUDA_VISIBLE_DEVICES=0,1,3,4,5 python  code/run_tacred.py \
  --do_train \
  --do_eval \
  --do_predict \
  --evaluate_during_training \
  --eval_steps 100 \
  --data_dir data/tacred \
  --data_cache_dir cache/tacred \
  --model trained_model \
  --per_device_train_batch_size 12 \
  --per_device_eval_batch_size 24 \
  --learning_rate 2e-5 \
  --num_train_epochs 10\
  --max_seq_length 128 \
  --output_dir tacred_dir 
