CUDA_VISIBLE_DEVICES=1,2,3,4,5,6,7 python code/run_tacred_trans.py \
  --do_train \
  --do_eval \
  --eval_test \
  --data_dir data/tacred \
  --data_cache_dir cache/tacred \
  --model bert-base-cased \
  --train_batch_size 128 \
  --eval_batch_size 128 \
  --learning_rate 2e-5 \
  --num_train_epochs 10 \
  --max_seq_length 128 \
  --output_dir tacred_dir
